Repository FRONTENDBOOTCAMP-13th/Final-01-1bone, pull requests merged in 2025-08, with the labels that each got.

#143 ✨ feat: refactor cart management and enhance product detail components
  next.config.ts
  src/app/shop/[productId]/page.tsx
  src/app/shop/cart/page.tsx
  src/components/features/shop/ProductDetail/CartAction.tsx
  src/components/features/shop/ProductDetail/CartContext.tsx
  src/components/features/shop/ProductDetail/OptionSelector.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/layout/header/Header.tsx
  src/data/functions/CartFetch.client.ts
  src/hooks/useCart.ts
  src/lib/auth.ts
  src/store/cart.store.ts
  src/store/cartStore.ts
  src/types/cart.ts
  src/types/product.ts
Labels: 🐞 BugFix, 🔨Retactor, ✨Feature, 🙋🏻‍♂️Help wanted

#155 ♻️ refactor: remove recent login info display & update login page UI
  public/images/etc/logo.webp
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/features/auth/LoginButton.tsx
  src/components/features/auth/SocialLoginButtons.tsx
  src/components/layout/moblie-frame/MobileFrame.tsx
Labels: 🔨Retactor, 🎨Style

#167 🐛 fix: improve cart button colors and responsiveness, and fix single item deletion state update
  src/app/shop/cart/page.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shopping-cart/CartItemCard.tsx
Labels: 🐞 BugFix, 🔨Retactor

#170 ✨ feat: add shopping list to My Page
  src/components/features/user/UserShopTab.tsx
  src/data/functions/OrderFetch.ts
  src/types/orders.ts
Labels: ✨Feature

#177 ♻️ refactor: add swipe gesture support to bottom sheet modal
  src/components/features/user/UserShopTab.tsx
  src/components/features/user/alarm/RandomModal.tsx
Labels: 🔨Retactor, 🎨Style, ✨Feature

#184 🔀 merge: feature/community/woomin into develop
  public/ChatGPT-Image-2025년-8월-5일-오전-12_34_46.svg
  public/images/character/character-write.webp
  public/images/icon/top.webp
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/app/favicon.ico
  src/app/shop/page.tsx
  src/components/common/Pagination.tsx
  src/components/common/ScrollTopButton.tsx
  src/components/features/(service)/notice/NoticeList.tsx
  src/components/features/community/comminity-update/FeedUpdateForm.tsx
  src/components/features/community/community-comment/CommentBottomSheet.tsx
  src/components/features/community/community-comment/CommentForm.tsx
  src/components/features/community/community-comment/CommentHeader.tsx
  src/components/features/community/community-comment/CommentInput.tsx
  src/components/features/community/community-comment/CommentItem.tsx
  src/components/features/community/community-comment/CommentList.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/community/community-comment/CommentOptionsModal.tsx
  src/components/features/community/community-comment/CommunityComment.tsx
  src/components/features/community/community-common/CommunityHeader.tsx
  src/components/features/community/community-create/FeedCategorySelect.tsx
  src/components/features/community/community-create/FeedContentInput.tsx
  src/components/features/community/community-create/FeedImageUpload.tsx
  src/components/features/community/community-create/FeedSubmitButton.tsx
  src/components/features/community/community-create/FeedWriteForm.tsx
  src/components/features/community/community-main/CommunityFeed.tsx
  src/components/features/community/community-main/CommunityFeedList.tsx
  src/components/features/community/community-main/CommunityFeedSkeleton.tsx
  src/components/features/community/community-main/CommunityMain.tsx
  src/components/features/community/community-main/CommunityPostActions.tsx
  src/components/features/community/community-main/CommunityPostContent.tsx
  src/components/features/community/community-main/CommunityPostHeader.tsx
  src/components/features/community/community-main/CommunityPostImage.tsx
  src/components/features/user/UserPreviewCard.tsx
  src/components/features/user/UserProfileSection.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/moblie-frame/MobileFrame.tsx
  src/components/layout/tabbar/Tabbar.tsx
  src/components/ui/skeleton.tsx
  src/data/actions/post.ts
  src/data/actions/user.ts
  src/data/functions/CommunityFetch.ts
  src/lib/auth.ts
  src/store/follow.store.ts
  src/store/followCount.store.ts
  src/types/api.ts
Labels: 🐞 BugFix, ⚡Enhancement, ✨Feature, 🟥P1: High

#185 ✨ feat: implement logout confirmation modal
  src/components/common/LogoutModal.tsx
  src/components/features/user/setting/LogoutButton.tsx
Labels: 🎨Style, ✨Feature

#187 ♻️ refactor: enhance cart and product detail UX with unified styles, bulk actions, and toast notifications
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
Labels: 🐞 BugFix, 🔨Retactor, 🎨Style, ✨Feature

#189 💄 style: improve UX by refining design, adding bulk delete, and showing toast on cart item delete
  src/app/shop/cart/page.tsx
  src/components/features/shopping-cart/CartItemCard.tsx
Labels: 🎨Style, ✨Feature

#214 ✨ feat: select/deselect all and individual items, improve cart checkbox UX
  src/app/shop/[productId]/page.tsx
  src/app/shop/cart/page.tsx
  src/components/features/shopping-cart/CartItemCard.tsx
  src/components/features/shopping-cart/CartList.tsx
  src/data/functions/CartFetch.client.ts
  src/store/cartStore.ts
  src/types/cart.ts
Labels: 🔨Retactor, ✨Feature

#216 ✨ feat: ordered products delete & ui detail
  src/app/live/LiveContent.tsx
  src/app/live/LiveData.tsx
  src/app/search/searchList.tsx
  src/app/shop/ShopList.tsx
  src/app/shop/cart/page.tsx
  src/app/shop/page.tsx
  src/app/shop/purchase/PurchaseClient.tsx
  src/components/features/live/LiveCalendar.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/shop/ShopProduct.tsx
  src/components/features/shopping-order/detail/purchase/PaymentSelector.tsx
  src/data/actions/orders.ts
  src/data/functions/CartFetch.server.ts
Labels: 🎨Style, ✨Feature

#221 🚨 hotfix: update middleware to enforce login flow and token refresh
  src/middleware.ts
Labels: 🐞 BugFix, 🔨Retactor

#219 🩹 coolfix: update ProductActionButtons border color, fix MD PICK rendering, and prevent null errors in recommendInfo
  src/components/features/shop/ProductDetail/ProductDetail.tsx
Labels: 🐞 BugFix, 🎨Style

#223 🔀 merge: feature/character/woomin into develop
  public/images/hobby/doll.webp
  public/images/hobby/dress.webp
  public/images/hobby/fashion.webp
  public/images/hobby/goods.webp
  public/images/hobby/homecafe.webp
  public/images/hobby/interior.webp
  public/images/hobby/perfume.webp
  public/images/hobby/running.webp
  src/app/hobby/page.tsx
  src/app/user/[id]/bookmark/page.tsx
  src/app/user/[id]/follow/page.tsx
  src/app/user/setting/page.tsx
  src/components/features/character/CharacterPage.tsx
  src/components/features/character/ChracterInfoModal.tsx
  src/components/features/character/ItemCard.tsx
  src/components/features/character/ItemPurchaseModal.tsx
  src/components/features/community/comminity-update/FeedUpdateForm.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/hobby/HobbyItem.tsx
  src/components/features/hobby/Savebutton.tsx
  src/components/features/user/UserPage.tsx
  src/components/layout/header/Header.tsx
  src/constant/hobby.ts
  src/constant/index.ts
  src/constant/item.ts
  src/constant/level.ts
  src/constant/message.ts
Labels: 🔨Retactor, 🎨Style

#227 🩹 coolfix: update design to match primary color
  src/app/not-found.tsx
Labels: 🔨Retactor, 🎨Style

#231 ✨ feat: display selected option info with product details in bottom sheet
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
Labels: 🐞 BugFix, 🔨Retactor, ✨Feature

#230 ✨ feat: add metadata to login page
  src/app/(auth)/login/page.tsx
Labels: ✨Feature

#233 🔀 merge: feature/order/woomin into develop
  src/app/shop/orderCompleted/[orderId]/page.tsx
  src/app/shop/purchase/PurchaseClient.tsx
  src/components/common/LogoutModal.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/shopping-order/detail/purchase/PaymentSelector.tsx
  src/components/features/shopping-order/detail/purchase/PaymentSummary.tsx
  src/components/features/shopping-order/detail/purchase/PurchaseAddress.tsx
  src/components/features/shopping-order/detail/purchase/PurchaseProductList.tsx
  src/data/actions/orders.ts
  src/middleware.ts
  src/types/orders.ts
Labels: ✨Feature

#236 🔀 merge: develop into main
  public/images/hobby/doll.webp
  public/images/hobby/dress.webp
  public/images/hobby/fashion.webp
  public/images/hobby/goods.webp
  public/images/hobby/homecafe.webp
  public/images/hobby/interior.webp
  public/images/hobby/perfume.webp
  public/images/hobby/running.webp
  src/app/(auth)/login/page.tsx
  src/app/hobby/page.tsx
  src/app/live/LiveContent.tsx
  src/app/live/LiveData.tsx
  src/app/not-found.tsx
  src/app/search/searchList.tsx
  src/app/shop/ShopList.tsx
  src/app/shop/[productId]/page.tsx
  src/app/shop/cart/page.tsx
  src/app/shop/orderCompleted/[orderId]/page.tsx
  src/app/shop/page.tsx
  src/app/shop/purchase/PurchaseClient.tsx
  src/app/user/[id]/bookmark/page.tsx
  src/app/user/[id]/follow/page.tsx
  src/app/user/setting/page.tsx
  src/components/common/LogoutModal.tsx
  src/components/features/character/CharacterPage.tsx
  src/components/features/character/ChracterInfoModal.tsx
  src/components/features/character/ItemCard.tsx
  src/components/features/character/ItemPurchaseModal.tsx
  src/components/features/community/comminity-update/FeedUpdateForm.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/hobby/HobbyItem.tsx
  src/components/features/hobby/Savebutton.tsx
  src/components/features/live/LiveCalendar.tsx
  src/components/features/live/LiveVideo.tsx
  src/components/features/shop/ProductDetail/CartAction.tsx
  src/components/features/shop/ProductDetail/CartContext.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/shop/ShopProduct.tsx
  src/components/features/shopping-cart/CartItemCard.tsx
  src/components/features/shopping-cart/CartList.tsx
  src/components/features/shopping-order/detail/purchase/PaymentSelector.tsx
  src/components/features/shopping-order/detail/purchase/PaymentSummary.tsx
  src/components/features/shopping-order/detail/purchase/PurchaseAddress.tsx
  src/components/features/shopping-order/detail/purchase/PurchaseProductList.tsx
  src/components/features/user/UserPage.tsx
  src/components/layout/header/Header.tsx
  src/constant/hobby.ts
  src/constant/index.ts
  src/constant/item.ts
  src/constant/level.ts
  src/constant/message.ts
  src/data/actions/orders.ts
  src/data/functions/CartFetch.client.ts
  src/data/functions/CartFetch.server.ts
  src/middleware.ts
  src/store/cartStore.ts
  src/types/cart.ts
  src/types/orders.ts
Labels: 🐞 BugFix, 🧪Test, 🔨Retactor, 🎨Style, ✨Feature

#243 🎫 assets: replace banner image
  public/ad-character.png
  public/ad-community.png
  public/ad-live.png
  public/ad-notice.png
  public/ad-shop.png
Labels: 🔨Retactor

#245 🔀 merge: feature/shop/woomin into develop
  public/images/etc/all.webp
  public/images/etc/bg-test.png
  public/images/etc/hobby-banner.webp
  public/images/etc/plant.webp
  public/images/etc/sofa-green.webp
  public/images/hobbism.png
  src/app/(support)/notice/[id]/page.tsx
  src/app/community/page.tsx
  src/app/layout.tsx
  src/app/shop/ShopList.tsx
  src/app/shop/page.tsx
  src/app/user/[id]/bookmark/page.tsx
  src/components/features/character/CharacterPage.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/shop/RandomHobby/RandomHobbyBtn.tsx
  src/components/features/shop/RandomHobby/RandomHobbyContent.tsx
  src/components/features/shop/ShopBanner.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/user/UserEditForm.tsx
  src/components/features/user/UserFeedTab.tsx
  src/components/features/user/UserPage.tsx
  src/components/features/user/UserShopTab.tsx
  src/components/features/user/setting/LoginInfo.tsx
  src/constant/item.ts
  src/utils/index.ts
Labels: 🐞 BugFix, ⚡Enhancement, 🎨Style, ✨Feature

#248 🔀 merge: develop into main
  README.md
  public/ad-character.png
  public/ad-community.png
  public/ad-live.png
  public/ad-notice.png
  public/ad-shop.png
  public/images/ayoung/banner/banner00.webp
  public/images/ayoung/hobby/hobby-01.webp
  public/images/ayoung/hobby/hobby-02.webp
  public/images/ayoung/hobby/hobby-03.webp
  public/images/ayoung/hobby/hobby-04.webp
  public/images/ayoung/hobby/hobby-05.webp
  public/images/ayoung/hobby/hobby-06.webp
  public/images/ayoung/hobby/hobby-07.webp
  public/images/etc/all.webp
  public/images/etc/bg-test.png
  public/images/etc/hobby-banner.webp
  public/images/etc/plant.webp
  public/images/etc/sofa-green.webp
  public/images/hobbism.png
  src/app/(support)/notice/[id]/page.tsx
  src/app/community/page.tsx
  src/app/layout.tsx
  src/app/shop/ShopList.tsx
  src/app/shop/[productId]/page.tsx
  src/app/shop/cart/page.tsx
  src/app/shop/page.tsx
  src/app/user/[id]/bookmark/page.tsx
  src/components/features/character/CharacterPage.tsx
  src/components/features/community/community-comment/CommentListItem.tsx
  src/components/features/shop/ProductDetail/OptionSelector.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/features/shop/RandomHobby/RandomHobbyBtn.tsx
  src/components/features/shop/RandomHobby/RandomHobbyContent.tsx
  src/components/features/shop/ShopBanner.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/shopping-cart/CartList.tsx
  src/components/features/user/UserEditForm.tsx
  src/components/features/user/UserFeedTab.tsx
  src/components/features/user/UserPage.tsx
  src/components/features/user/UserShopTab.tsx
  src/components/features/user/setting/LoginInfo.tsx
  src/constant/item.ts
  src/utils/index.ts
Labels: 🐞 BugFix, ⚡Enhancement, 🔨Retactor, 🎨Style, ✨Feature

#250 🔀 merge: hoxfix/og-graph/woomin into develop
  src/app/layout.tsx
Labels: 🐞 BugFix

#251 🔀 merge: develop into main
  src/app/layout.tsx
Labels: 🐞 BugFix
