Repository FRONTENDBOOTCAMP-13th/Final-01-1bone, pull requests merged in 2025-07, with the labels that each got.

#2 🔧 conf: comment conventions and libraries setting
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  .vscode/settings.json
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/components/ui/.gitkeep
  src/components/ui/button.stories.ts
  vitest.config.ts
  vitest.shims.d.ts
Labels: ⚙Setting, 🟢Easy, 🟥P1: High

#4 🔧 conf: create sample image folders
  public/images/.gitkeep
  public/images/ayoung/.gitkeep
  public/images/hyunji/.gitkeep
  public/images/inhawn/.gitkeep
  public/images/woomin/.gitkeep
  public/images/youngchan/.gitkeep
Labels: ⚙Setting, 🟢Easy

#11 🔧 conf: created subfolders under components directory
  src/components/features/auth/index.ts
  src/components/features/character/index.ts
  src/components/features/community/index.ts
  src/components/features/live/index.ts
  src/components/features/shop/index.ts
  src/components/features/user/index.ts
Labels: ⚙Setting

#16 💄 feat: create Login component
  package-lock.json
  src/components/features/auth/LoginButton.tsx
Labels: 🎨Style

#18 💄 feat: create Shop main component
  package-lock.json
  package.json
  public/images/ayoung/ad/ad01.webp
  public/images/ayoung/ad/ad02.webp
  public/images/ayoung/banner/banner01.webp
  public/images/ayoung/banner/banner02.webp
  public/images/ayoung/banner/banner03.webp
  public/images/ayoung/products/dress/ankrouge-03-01.webp
  public/images/ayoung/products/dress/ankrouge-03-02.webp
  src/components/features/shop/ShopAd.stories.tsx
  src/components/features/shop/ShopAd.tsx
  src/components/features/shop/ShopBanner.stories.tsx
  src/components/features/shop/ShopBanner.tsx
  src/components/features/shop/ShopCategory.stories.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/shop/ShopProduct.stories.tsx
  src/components/features/shop/ShopProduct.tsx
Labels: 🎨Style

#20 ✨ feat: add common components and routing folders
  package-lock.json
  package.json
  public/fonts/.gitkeep
  public/fonts/PretendardVariable.woff2
  src/app/character/page.tsx
  src/app/community/page.tsx
  src/app/layout.tsx
  src/app/live/page.tsx
  src/app/shop/[productId]/page.tsx
  src/app/shop/page.tsx
  src/app/user/page.tsx
  src/components/layout/Footer/.gitkeep
  src/components/layout/Header/.gitkeep
  src/components/layout/Tabbar/.gitkeep
  src/components/layout/header/Header.tsx
  src/components/layout/moblie-frame/MobileFrame.tsx
  src/components/layout/tabbar/BarItem.stories.tsx
  src/components/layout/tabbar/BarItem.tsx
  src/components/layout/tabbar/TabBar.stories.tsx
  src/components/layout/tabbar/Tabbar.tsx
  src/constant/index.ts
  src/constant/tabBarItems.ts
  src/styles/globals.css
Labels: ⚙Setting, 🎨Style, ✨Feature

#22 💄 Style: Shop Main Page UI
  src/app/shop/page.tsx
  src/components/features/shop/ShopAd.tsx
  src/components/features/shop/ShopBanner.tsx
  src/components/features/shop/ShopCategory.tsx
  src/components/features/shop/ShopLiveProducts.tsx
  src/components/features/shop/ShopProduct.tsx
Labels: ✨Feature

#24 ✨ feat: add login feature with UI images
  package-lock.json
  package.json
  public/googleIcon.svg
  public/images/youngchan/asicsshoes-02.webp
  public/images/youngchan/asicsshoesInfo-02.webp
  public/images/youngchan/byredo-02.webp
  public/images/youngchan/byredoInfo-02.webp
  public/images/youngchan/cap-03.webp
  public/images/youngchan/capInfo-03.webp
  public/images/youngchan/diptyque-01.webp
  public/images/youngchan/diptyqueInfo-01.webp
  public/images/youngchan/energyjel-02.webp
  public/images/youngchan/energyjelInfo-02.webp
  public/images/youngchan/gun-02.webp
  public/images/youngchan/gunInfo-02.webp
  public/images/youngchan/hairband-01.webp
  public/images/youngchan/hairbandInfo-01.webp
  public/images/youngchan/knee-02.webp
  public/images/youngchan/kneeInfo-02.webp
  public/images/youngchan/lelabo-01.webp
  public/images/youngchan/lelabo-02.webp
  public/images/youngchan/lelabo-03.webp
  public/images/youngchan/lelaboInfo.webp
  public/images/youngchan/maison-02.webp
  public/images/youngchan/maisonInfo-02.webp
  public/images/youngchan/nikeshoes-01.webp
  public/images/youngchan/nikeshoes-03.webp
  public/images/youngchan/nikeshoesInfo-01.webp
  public/images/youngchan/nikeshoesInfo-03.webp
  public/images/youngchan/penhaligons-01.webp
  public/images/youngchan/penhaligonsInfo-01.webp
  public/images/youngchan/socks-02.webp
  public/images/youngchan/socksInfo-02.webp
  public/images/youngchan/vest-03.webp
  public/images/youngchan/vestInfo-03-1.webp
  public/images/youngchan/vestInfo-03-2.webp
  public/kakaoIcon.svg
  public/logo.svg
  public/naverIcon.svg
  src/app/(auth)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/components/features/auth/LoginButton.tsx
  src/context/AuthContext.tsx
Labels: ✨Feature

#26 ♿ wai: Add ARIA attributes for web accessibility
  public/images/hyunji/interior_03.webp
  public/images/hyunji/interior_03_01.webp
  public/images/hyunji/interior_04.webp
  public/images/hyunji/interior_04_01.webp
  public/images/hyunji/interior_05.webp
  public/images/hyunji/interior_05_01.webp
  src/components/features/shop/ProductDetail/OptionSelector.tsx
Labels: 🔨Retactor, 🟥P1: High

#28 💄style: create cart components and add related images
  public/check-off.svg
  public/check-on.svg
  public/delete.svg
  public/minus.svg
  public/plus.svg
  src/components/features/shopping-cart/CartItemCard.tsx
Labels: 🎨Style

#32 🐛 fix: resolve login issue
  src/app/api/auth/[...nextauth]/route.ts
Labels: 🐞 BugFix

#40 💄 style: implement community post creation UI
  src/app/community/write/page.tsx
  src/components/features/community/community-create/FeedImageUpload.tsx
Labels: 🎨Style

#42 💄 style: complete UI for community myfeed page
  src/app/user/myfeed/page.tsx
Labels: 🎨Style

#47 ✨ feat: implement UI and logic for comment, share, and bookmark in community feed
  src/app/user/myfeed/layout.tsx
  src/components/features/community/community-bookmark/BookmarkFeedCard.tsx
  src/components/features/community/community-detail/CommentInput.tsx
  src/components/features/community/community-detail/CommentItem.tsx
Labels: 🎨Style, ✨Feature

#51 ✨ feat: add auth guard and token refresh logic
  middleware.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/components/features/auth/TokenSync.tsx
  src/store/auth.store.ts
Labels: ⚡Enhancement, ✨Feature

#57 ✨ feat: Add product selection & dynamic pricing
  src/app/shop/cart/page.tsx
Labels: ✨Feature

#61 ✨ feat: implement reply CRUD functionality for community posts
  src/app/api/comments/route.ts
  src/app/community/[id]/layout.tsx
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/components/features/community/community-bookmark/BookmarkFeedCard.tsx
  src/components/features/community/community-common/CommunityHeader.tsx
  src/components/features/community/community-create/FeedSubmitButton.tsx
  src/components/features/community/community-detail/CommentInput.tsx
  src/components/features/community/community-detail/CommentItem.tsx
  src/components/features/community/community-detail/CommentOptionsModal.tsx
  src/components/features/community/community-detail/CommentSection.tsx
  src/components/features/community/community-main/CommunityMain.tsx
  src/components/features/community/community-main/CommunityMainHeader.tsx
  src/data/functions/CommentsFetch.ts
Labels: 📫API, ✨Feature

#65 🐛 fix: fix typos in multiple function names
  src/app/api/comments/route.ts
  src/components/features/community/community-detail/CommentInput.tsx
  src/components/features/community/community-main/CommunityMain.tsx
  src/components/features/community/community-main/CommunityMainHeader.tsx
Labels: 🐞 BugFix

#67 💄 style: Live Component, Page UI
  package-lock.json
  package.json
  src/app/live/LiveDataUI.tsx
  src/app/live/page.tsx
  src/components/features/live/LiveBuyBtn.stories.tsx
  src/components/features/live/LiveBuyBtn.tsx
  src/components/features/live/LiveCalendar.stories.tsx
  src/components/features/live/LiveCalendar.tsx
  src/components/features/live/LiveCalendarBtn.tsx
  src/components/features/live/LiveComment.tsx
  src/components/features/live/LiveProgress.stories.tsx
  src/components/features/live/LiveProgress.tsx
  src/components/features/live/LiveVideo.tsx
  src/data/functions/LiveProductFetch.ts
  src/data/functions/ProductFetch.ts
Labels: 🎨Style

#68 💄 style: complete 404 error and loading page UI
  public/clock.png
  src/app/loading.tsx
  src/app/not-found.tsx
  src/styles/globals.css
Labels: 🎨Style

#76 ✨ feat: Implemented integrated logic for navigating to the product detail page, passing product ID, cleaning up UI, defining types, and fetching data
  src/app/shop/[productId]/page.tsx
  src/components/features/shop/ProductDetail/CartContext.tsx
  src/components/features/shop/ProductDetail/ProductAction.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/features/shop/ShopProduct.tsx
  src/data/functions/ProductFetch.ts
  src/types/interface/product.ts
Labels: 🐞 BugFix, 🔨Retactor, 🎨Style, ✨Feature, 🟥P1: High

#78 ♻️ refactor: move OAuth signup URL to .env
  middleware.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/comments/route.ts
  src/data/functions/CommentsFetch.ts
  src/store/auth.store.ts
Labels: 🔨Retactor

#79 ✨ feat: add image, phone, and address to user data
  api/bruno/1bone/회원/social Login.bru
  api/bruno/1bone/회원/회원 조회.bru
  src/app/api/auth/[...nextauth]/route.ts
  src/components/features/auth/TokenSync.tsx
  src/store/auth.store.ts
Labels: ✨Feature

#87 🐛 fix: Add NEXTAUTH_SECRET for production auth
  package-lock.json
  src/app/api/auth/[...nextauth]/route.ts
Labels: 🐞 BugFix

#92 🐛 fix: separate authOptions from route handler
  src/app/api/auth/[...nextauth]/route.ts
  src/lib/auth.ts
Labels: 🐞 BugFix

#95 🚨 hotfix: resolve build error
  src/app/live/LiveOverlay.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/store/live.store.ts
Labels: 🐞 BugFix

#96 🔀 merge: develop into main
  src/app/live/LiveOverlay.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/store/live.store.ts
Labels: 🐞 BugFix

#100 🔀 merge: develop into main
  src/app/community/[id]/layout.tsx
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/app/community/write/page.tsx
Labels: 🐞 BugFix, 🧪Test

#110 ♻️ refactor: Refactor Shop/Live & edit top btn style
  src/app/live/LiveContent.tsx
  src/app/live/LiveData.tsx
  src/app/search/page.tsx
  src/app/search/searchList.tsx
  src/app/shop/ShopList.tsx
  src/app/shop/page.tsx
  src/app/shop/randomHobby/page.tsx
  src/components/common/SmallLoading.tsx
  src/components/common/TopButton.tsx
  src/components/features/shop/RandomHobby/RandomHobbyBtn.tsx
  src/components/features/shop/RandomHobby/RandomHobbyContent.tsx
  src/components/features/shop/RecommendProducts.tsx
  src/components/features/shop/ShopLiveProducts.tsx
  src/components/features/shop/ShopProduct.tsx
  src/data/functions/AllProductFetch.ts
  src/data/functions/ProductFetch.ts
  src/store/live.store.ts
Labels: 🔨Retactor, 🎨Style

#112 ♻️ refactor: improve dynamic UI and discount logic by option
  src/app/shop/[productId]/page.tsx
  src/components/features/shop/ProductDetail/OptionSelector.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/types/product.ts
Labels: 🐞 BugFix, 🔨Retactor, ✨Feature

#123 ✨ feat: add recent login account memory and display feature
  src/app/(auth)/login/page.tsx
  src/components/features/auth/RecentLogin.tsx
  src/components/features/auth/SocialLoginButtons.tsx
  src/components/features/user/setting/LogoutButton.tsx
  src/lib/signInHandler.ts
Labels: ✨Feature

#127 ✨ feat: add dynamic option UI, discount logic, and cart routing; refactor for DB schema, type, and props structure consistency
  src/app/shop/[productId]/page.tsx
  src/components/features/shop/ProductDetail/CartContext.tsx
  src/components/features/shop/ProductDetail/OptionSelector.tsx
  src/components/features/shop/ProductDetail/ProductDetail.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/layout/moblie-frame/MobileFrame.tsx
  src/types/cart.ts
  src/types/product.ts
Labels: 🐞 BugFix, 🔨Retactor

#129 🐛 fix: show option dropdown when clicking 'Buy Now' button
  src/app/shop/cart/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/features/shop/ProductDetail/CartAction.tsx
  src/components/features/shop/ProductDetail/ProductAction.tsx
  src/components/features/shop/ProductDetail/ProductDetailClient.tsx
  src/components/features/shopping-cart/CartIcon.tsx
  src/components/layout/header/Header.tsx
  src/data/functions/CartFetch.client.ts
  src/data/functions/OrderFetch.ts
  src/data/functions/ProductFetch.ts
  src/hooks/useCart.ts
  src/store/cart.store.ts
  src/types/cart.ts
Labels: 🐞 BugFix

#135 🔀 merge feature/mypage/woomin into develop
  package-lock.json
  package.json
  public/images/character/character-sleep.webp
  src/app/(support)/layout.tsx
  src/app/(support)/notice/[id]/page.tsx
  src/app/(support)/notice/page.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/app/user/[id]/page.tsx
  src/app/user/edit/page.tsx
  src/app/user/setting/page.tsx
  src/components/common/Pagination.tsx
  src/components/common/icons.tsx
  src/components/features/(service)/notice/NoticeList.tsx
  src/components/features/character/ItemPurchaseModal.tsx
  src/components/features/user/UserEditForm.tsx
  src/components/features/user/UserFeedTab.tsx
  src/components/features/user/UserPage.tsx
  src/components/features/user/UserPreviewCard.tsx
  src/components/features/user/UserProfileSection.tsx
  src/components/features/user/follow/FollowSection.tsx
  src/components/features/user/setting/AddressForm.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/tabbar/Tabbar.tsx
  src/constant/item.ts
  src/data/actions/bookmark.ts
  src/data/actions/post.ts
  src/data/actions/user.ts
  src/hooks/pageination.hook.ts
  src/store/follow.store.ts
Labels: ✨Feature, 🟨P2: Medium
